@startuml

hide empty methods

!procedure $schema($name)
package "$name" as $name <<Rectangle>>
!endprocedure

!procedure $table($name)
entity "<b>$name</b>" as $name << (T, Orange) table >>
!endprocedure

!procedure $view($name)
entity "<b>$name</b>" as $name << (V, Aquamarine) view >>
!endprocedure

!procedure $pk($name)
<color:#GoldenRod><&key></color> <b>$name</b>
!endprocedure

!procedure $fk($name)
<color:#Silver><&key></color> $name
!endprocedure

!procedure $column($name)
{field} <color:#White><&media-record></color> $name
!endprocedure

title "Toast Core"

left to right direction

$schema("Users") {
    $table("Users") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $column("username") VARCHAR(50) UNIQUE
        * $column("password") VARCHAR(255)
        * $column("role") VARCHAR(100)
          $column("discordID") VARCHAR(255) UNIQUE
    }

    $table("MindustryUserServerData") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("mindustryUserID") INTEGER
        * $column("serverID") VARCHAR(255)
        * $column("xp") INTEGER DEFAULT 0
        * $column("playTime") BIGINT DEFAULT 0
        * $column("activePlayTime") BIGINT DEFAULT 0
    }

    $table("MindustryUser") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
          $fk("userID") INTEGER
        * $column("mindustryUUID") VARCHAR(255) UNIQUE
    }

    $table("MindustryUSID") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("mindustryUserServerDataID") INTEGER
        * $column("MindustryUSID") VARCHAR(64) UNIQUE
    }

    $table("MindustryUserIPAddresses") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("ipAddressID") INTEGER
        * $fk("mindustryUserID") INTEGER
    }

    $table("MindustryUserMindustryNames") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("mindustryNameID") INTEGER
        * $fk("mindustryUserID") INTEGER
    }

    $table("IPAddresses") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $column("ipAddress") INTEGER UNIQUE
    }

    $table("MindustryNames") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $column("name") VARCHAR(50) UNIQUE
        * $column("strippedName") VARCHAR(50)
    }

    $table("UserKick") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $column("reason") TEXT
        * $column("kickedAt") DATETIME
        * $column("kickEndAt") DATETIME
        * $column("kickType") VARCHAR(50) COMMENT Kick, VoteKick
          $fk("mindustryUserID") INTEGER
          $fk("targetUserID") INTEGER
        * $fk("targetMindustryUserID") INTEGER
    }

    $table("UserVoteKick") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("userKickID") INTEGER
        * $fk("voteKickStarterUserID") INTEGER
        * $column("requiredVotes") SHORT
        * $column("result") VARCHAR(50)
    }

    $table("UserVoteKickVotes") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("mindustryUserID") INTEGER
        * $fk("userVoteKickID") INTEGER
        * $column("vote") BOOLEAN
    }

    $table("UserBan") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $column("reason") TEXT
        * $column("bannedAt") DATETIME
        * $fk("userID") INTEGER
          $fk("targetUserID") INTEGER
        * $fk("targetMindustryUserID") INTEGER
    }

    Users::id ||--o{ MindustryUser::userID
    MindustryUserServerData::mindustryUserID }--|| MindustryUser::id

    MindustryUSID::mindustryUserServerDataID }--|| MindustryUserServerData::id

    MindustryUser::id ||--{ MindustryUserIPAddresses::mindustryUserID
    IPAddresses::id ||--{ MindustryUserIPAddresses::ipAddressID
    MindustryUser::id ||--{ MindustryUserMindustryNames::mindustryUserID
    MindustryNames::id ||--{ MindustryUserMindustryNames::mindustryNameID

    UserKick::mindustryUserID }o--|| MindustryUser::id
    UserKick::targetUserID }o--|| Users::id
    UserKick::targetMindustryUserID }--|| MindustryUser::id

    UserVoteKick::voteKickStarterUserID }o--|| Users::id
    UserVoteKick::userKickID }o--|| UserKick::id

    UserVoteKickVotes::userVoteKickID }o--|| UserVoteKick::id
    UserVoteKickVotes::mindustryUserID }o--|| MindustryUser::id

    UserBan::userID }--|| Users::id
    UserBan::targetUserID }o--|| Users::id
    UserBan::targetMindustryUserID }--|| MindustryUser::id
}

$schema("Map") {
    $table("Map") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $column("name") VARCHAR(60)
        * $column("description") TEXT
        * $column("author") VARCHAR(50)
        * $fk("submitterUserID") INTEGER
        * $column("width") INTEGER
        * $column("height") INTEGER
        * $column("file") MEDIUMBLOB
        * $column("createdAt") DATETIME
        * $column("updatedAt") DATETIME
        * $column("isActive") BOOLEAN
    }

    $table("MapGameMode") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("mapID") INTEGER
        * $column("gameMode") VARCHAR(100)
    }

    $table("MapRating") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("mapID") INTEGER
        * $fk("userID") INTEGER
        * $fk("gameHistoryID") INTEGER
        * $column("rating") Integer
        * $column("description") TEXT
    }

    Map::submitterUserID ||---|| Users.Users::id
    MapRating::mapID }o--|| Map::id
    MapRating::userID |o--|| Users.Users::id

    MapGameMode::mapID }--|| Map::id
}

$schema("GameHistory") {
    $table("GameHistory") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $column("createdAt") DATETIME
        * $column("playTime") BIGINT
        * $fk("mapID") INTEGER
        * $column("gameModeID") VARCHAR(255)
        * $column("serverID") VARCHAR(255)
        * $column("winnerTeam") VARCHAR(255)
        * $column("unitsCreated") INTEGER
        * $column("enemiesKilled") INTEGER
        * $column("wavesLasted") INTEGER
        * $column("buildingsConstructed") INTEGER
        * $column("buildingsDeconstructed") INTEGER
        * $column("buildingsDestroyed") INTEGER
    }

    $table("GameHistoryPlayer") {
        * $pk("id") INTEGER AUTOINCREMENT UNIQUE
        * $fk("gameHistoryID") INTEGER
        * $fk("userID") INTEGER COMMENT In seconds
        * $column("playTime") BIGINT
        * $column("activePlayTime") BIGINT
    }

    GameHistoryPlayer::gameHistoryID }o--|| GameHistory::id
    GameHistoryPlayer::userID }o--|| Users.Users::id
    GameHistory::mapID }o--|| Map.Map::id
}

Map.MapRating::gameHistoryID }o--|| GameHistory.GameHistory::id

@enduml