version: '3.8'

# Development
services:
  discovery-redis:
    image: redis:7.2.4-alpine
    init: true
    volumes:
      - ./dev/discovery-redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./dev/verify-discord-redis/users.acl:/usr/local/etc/redis/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: [ 'CMD-SHELL', 'redis-cli ping | grep PONG' ]
    networks:
      - toast

  verify-discord-redis:
    image: redis:7.2.4-alpine
    init: true
    volumes:
      - ./dev/verify-discord-redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./dev/verify-discord-redis/users.acl:/usr/local/etc/redis/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    healthcheck:
      test: [ 'CMD-SHELL', 'redis-cli ping | grep PONG' ]
    networks:
      - toast


  database:
    image: mariadb:lts
    init: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toast
    volumes:
      - ./dev/mysql/my.cnf:/etc/mysql/my.cnf
      - data:/var/lib/mysql
    command: bash -c "chmod 644 /etc/mysql/*.cnf && /usr/local/bin/docker-entrypoint.sh mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          'CMD',
          '/usr/local/bin/healthcheck.sh',
          '--su-mysql',
          '--connect',
          '--innodb_initialized',
        ]
    networks:
      - toast

  rabbitMQ:
    image: rabbitmq:3.12-management
    init: true
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dev/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
    networks:
      - toast

volumes:
  data:
  rabbitmq-data:

networks:
  toast: