version: '3.8'

services:
  portainer-agent:
    image: portainer/agent:2.19.4
    ports:
      - "9001:9001"
    healthcheck:
      test: "wget --no-check-certificate --no-verbose --tries=1 --spider --header='Content-Type:application/json' http://127.0.0.1:9001/ping || exit 1"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - toast
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 40M
          cpus: '0.5'

networks:
  toast: