version: '3.8'

services:
  pvp-server:
    build:
      context: .
      dockerfile: ./prod/Dockerfiles/mindustry.Dockerfile
    init: true
    tty: true
    stdin_open: true
    stop_signal: SIGTERM
    stop_grace_period: 15s
    ports:
      - "6567:6567/tcp"
      - "6567:6567/udp"
    volumes:
      - ./prod/maps/pvp:/app/config/maps/
      - pvp-server-saves:/app/config/saves/
    networks:
      - toast
    env_file:
      - ./prod/.env.common
    environment:
      SERVER: PvP
      PORT: 6567
    healthcheck:
      test: [ 'CMD-SHELL', 'ss -ltu | grep $$PORT | wc -l | grep 2' ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 1m
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '1'

  portainer-agent:
    image: portainer/agent:2.19.4-alpine
    init: true
    ports:
      - "9001:9001"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - toast
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 40M
          cpus: '0.5'

volumes:
  pvp-server-saves:

networks:
  toast: